#!/bin/python

# Given an array of integers, find the sum of its elements.

# For example, if the array ar = [1,2,3], 1+2+3 = 6 , so return 6

# .
# Function Description

# Complete the simpleArraySum function in the editor below. It must return the sum of the array elements as an integer.

# simpleArraySum has the following parameter(s):

#     ar: an array of integers

# Input Format

# The first line contains an integer, n, denoting the size of the array.
# The second line contains n space-separated integers representing the array's elements.

# Constraints 0 < n, a[i] < = 1000

# Output Format

# Print the sum of the array's elements as a single integer.

# Sample Input:
# 6
# 1 2 3 4 10 11

# Sample Output:
# 31

# Test case 1:
# Input:
# 3
# -1 1 0

# Output:
# 0

# Test case 2:
# Input:
# 6
# 1 2 3 4 10 11

# Output: 
# 31

# Test case 3:
# Input:
# 5
# -3 0 1 2 4

# Output:
# 4


import math
import os
import random
import re
import sys
import functools

#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

def simpleArraySum(ar):
    # Write your code here
    sum = functools.reduce(lambda a, b: a+b, ar)
    return sum

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(raw_input().strip())

    ar = map(int, raw_input().rstrip().split())

    result = simpleArraySum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
